[tool.poetry]
name = "eth-rpc"
version = "0.1.0"
description = "A lightweight Ethereum RPC written in python"
authors = ["gabedonnan <47415809+gabedonnan@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
requests = "^2.31.0"
websockets = "^11.0.3"
jsonschema = "^4.18.4"
eth-typing = "^3.4.0"
eth-utils = "^2.2.0"
dataclasses-json = "^0.5.13"
eth-account = "^0.9.0"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
